// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Z9_fBpBniXQ4q9s2EeZ8jp8ik7LDbQo',
    appId: '1:574536098944:web:e215c64b494162e0fdb265',
    messagingSenderId: '574536098944',
    projectId: 'fir-codelandia',
    authDomain: 'fir-codelandia.firebaseapp.com',
    storageBucket: 'fir-codelandia.appspot.com',
    measurementId: 'G-JRVDHG9F6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByG6AykuCfWtgkRDZGv7Uq8rn9tfj7Aws',
    appId: '1:574536098944:android:53207d2b0f041696fdb265',
    messagingSenderId: '574536098944',
    projectId: 'fir-codelandia',
    storageBucket: 'fir-codelandia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmhm0guj5eUnim_7asfkcIC8ww6gsc4eI',
    appId: '1:574536098944:ios:b7896e2f0a254583fdb265',
    messagingSenderId: '574536098944',
    projectId: 'fir-codelandia',
    storageBucket: 'fir-codelandia.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebaseStorageExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmhm0guj5eUnim_7asfkcIC8ww6gsc4eI',
    appId: '1:574536098944:ios:238388e76282dc5afdb265',
    messagingSenderId: '574536098944',
    projectId: 'fir-codelandia',
    storageBucket: 'fir-codelandia.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebaseStorageExample.RunnerTests',
  );
}
